language: python
python:
  - "2.6"
  - "2.7"
before_install:
  - export DJANGO_SETTINGS_MODULE=celery_haystack.test_settings
install:
  - pip install -e .
  - pip install -r requirements/$HAYSTACK.txt Django==$DJANGO
before_script:
  - flake8 celery_haystack --ignore=E501
script:
  - coverage run --branch --source=celery_haystack `which django-admin.py` test celery_haystack
  - coverage report --omit=celery_haystack/test*
env:
  - DJANGO=1.3.7 HAYSTACK=v1
  - DJANGO=1.3.7 HAYSTACK=v2
  - DJANGO=1.4.5 HAYSTACK=v1
  - DJANGO=1.4.5 HAYSTACK=v2
  - DJANGO=1.5 HAYSTACK=v1
  - DJANGO=1.5 HAYSTACK=v2
