# This Action uses minimal steps to run in ~5 seconds to rapidly:
# find typos in the codebase using codespell, and
# lint Python code using ruff and provide intuitive GitHub Annotations to contributors.
# https://github.com/codespell-project/codespell#readme
# https://docs.astral.sh/ruff
name: codespell_and_ruff
on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]
jobs:
  codespell_and_ruff:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: pip install --user codespell[toml] ruff
    - run: codespell  # --ignore-words-list="" --skip="*.css,*.js,*.lock,*.po"
    - run: ruff --output-format=github --target-version=py38 .
