# This Action uses minimal steps to run in ~5 seconds to rapidly:
# find typos in the codebase using codespell, and
# lint Python code using ruff and provide intuitive GitHub Annotations to contributors.
# https://github.com/codespell-project/codespell#readme
# https://beta.ruff.rs
name: codespell_and_ruff
on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: pip install --user codespell[toml] ruff
    - run: codespell  # --ignore-words-list="" --skip="*.css,*.js,*.lock,*.po"
    - run: ruff --format=github --ignore=E401,E731,F401 --target-version=py38 .
